Add on-exit hoook

diff --git a/res-man b/res-man
--- a/res-man
+++ b/res-man
@@ -42,6 +42,12 @@ backup() {
 		error "Backup error"
 }
 
+on_exit() {
+	[ -f "$ON_EXIT" ] || return 0
+
+	"$ON_EXIT" "$JOB_NAME" || error "Exit script failed"
+}
+
 check() {
 	restic check --verbose --read-data-subset "${CHECK_SUBSET:-"2%"}" ||
 		error "Check error"
@@ -100,6 +106,8 @@ daily() {
 	else
 		echo "Daily job finished with errors."
 	fi
+
+	on_exit
 }
 
 help() {
@@ -114,6 +122,7 @@ EXIT_STATUS=0
 CONFIG_DIR="${RESTIC_CONFIG_DIR:-/etc/restic}"
 ON_ERROR=$CONFIG_DIR/${ON_ERROR:-on_error.sh}
 ON_SUCCESS=$CONFIG_DIR/${ON_SUCCESS:-on_success.sh}
+ON_EXIT=$CONFIG_DIR/${ON_EXIT:-on_exit.sh}
 PREPARE_SCRIPT=$CONFIG_DIR/${PREPARE_SCRIPT:-prepare.sh}
 JOB_NAME="${1:-}"
 [ "$JOB_NAME" = "" ] && help
